import sqlite3
from contextlib import contextmanager

DB_PATH = "mfd_local.db"


@contextmanager
def get_conn():
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db() -> None:
    with get_conn() as conn:
        conn.executescript("""
        PRAGMA journal_mode = WAL;
        PRAGMA foreign_keys = ON;

        -- ── BSE ──────────────────────────────────────────────────────────────

        CREATE TABLE IF NOT EXISTS clients (
            client_code         TEXT PRIMARY KEY,
            member_code         TEXT,
            first_name          TEXT,
            middle_name         TEXT,
            last_name           TEXT,
            pan                 TEXT,
            tax_status          TEXT,
            gender              TEXT,
            dob                 TEXT,
            occupation_code     TEXT,
            holding_nature      TEXT,
            kyc_type            TEXT,
            ckyc_number         TEXT,
            aadhaar_updated     TEXT,
            email               TEXT,
            mobile              TEXT,
            address1            TEXT,
            address2            TEXT,
            address3            TEXT,
            city                TEXT,
            state               TEXT,
            pincode             TEXT,
            country             TEXT,
            created_at          TEXT,
            last_modified_at    TEXT
        );

        CREATE TABLE IF NOT EXISTS clients_bank (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            client_code     TEXT NOT NULL REFERENCES clients(client_code) ON DELETE CASCADE,
            bank_seq        INTEGER,
            account_type    TEXT,
            account_no      TEXT,
            micr_no         TEXT,
            ifsc_code       TEXT,
            bank_name       TEXT,
            bank_branch     TEXT,
            is_default      TEXT,
            status          TEXT,
            created_at      TEXT,
            UNIQUE(client_code, account_no)
        );

        CREATE TABLE IF NOT EXISTS clients_nominee (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            client_code     TEXT NOT NULL REFERENCES clients(client_code) ON DELETE CASCADE,
            nominee_seq     INTEGER,
            name            TEXT,
            relationship    TEXT,
            percentage      REAL,
            is_minor        TEXT,
            dob             TEXT,
            guardian_name   TEXT,
            guardian_pan    TEXT,
            pan             TEXT,
            email           TEXT,
            mobile          TEXT,
            address1        TEXT,
            address2        TEXT,
            address3        TEXT,
            city            TEXT,
            pincode         TEXT,
            UNIQUE(client_code, nominee_seq)
        );

        CREATE TABLE IF NOT EXISTS bse_xsip (
            xsip_regn_no        TEXT PRIMARY KEY,
            client_code         TEXT,
            client_name         TEXT,
            member_code         TEXT,
            status              TEXT,
            amc_name            TEXT,
            rta_scheme_code     TEXT,
            scheme_name         TEXT,
            frequency_type      TEXT,
            start_date          TEXT,
            end_date            TEXT,
            installments_amt    REAL,
            no_of_installments  INTEGER,
            first_order         TEXT,
            folio_no            TEXT,
            mandate_id          TEXT,
            euin                TEXT,
            sub_broker          TEXT,
            regn_date           TEXT,
            pg_bank_ref_no      TEXT,
            remarks             TEXT,
            primary_email       TEXT,
            primary_mobile      TEXT,
            upload_batch        TEXT
        );

        -- ── CAMS ────────────────────────────────────────────────────────────

        CREATE TABLE IF NOT EXISTS cams_folio (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            folio_no            TEXT,
            inv_name            TEXT,
            pan_no              TEXT,
            product             TEXT,
            sch_name            TEXT,
            amc_code            TEXT,
            clos_bal            REAL,
            rupee_bal           REAL,
            rep_date            TEXT,
            address1            TEXT,
            address2            TEXT,
            address3            TEXT,
            city                TEXT,
            pincode             TEXT,
            email               TEXT,
            mobile_no           TEXT,
            inv_dob             TEXT,
            occupation          TEXT,
            tax_status          TEXT,
            holding_nature      TEXT,
            jnt_name1           TEXT,
            jnt_name2           TEXT,
            joint1_pan          TEXT,
            joint2_pan          TEXT,
            bank_name           TEXT,
            branch              TEXT,
            ac_type             TEXT,
            ac_no               TEXT,
            ifsc_code           TEXT,
            nom_name            TEXT,
            nom_relation        TEXT,
            nom_percentage      REAL,
            nom_email           TEXT,
            nom2_name           TEXT,
            nom2_relation       TEXT,
            nom2_percentage     REAL,
            nom3_name           TEXT,
            nom3_relation       TEXT,
            nom3_percentage     REAL,
            broker_code         TEXT,
            folio_date          TEXT,
            folio_old           TEXT,
            scheme_folio_number TEXT,
            gst_state_code      TEXT,
            upload_batch        TEXT,
            UNIQUE(folio_no, product, rep_date)
        );

        CREATE TABLE IF NOT EXISTS cams_transactions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            amc_code        TEXT,
            folio_no        TEXT,
            product         TEXT,
            scheme          TEXT,
            inv_name        TEXT,
            pan             TEXT,
            trxn_no         TEXT,
            trxn_type       TEXT,
            trxn_mode       TEXT,
            trxn_status     TEXT,
            trxn_subtype    TEXT,
            trade_date      TEXT,
            post_date       TEXT,
            nav             REAL,
            units           REAL,
            amount          REAL,
            stamp_duty      REAL DEFAULT 0,
            stt             REAL DEFAULT 0,
            sip_trxn_no     TEXT,
            request_ref_no  TEXT,
            igst_amount     REAL DEFAULT 0,
            cgst_amount     REAL DEFAULT 0,
            sgst_amount     REAL DEFAULT 0,
            ac_no           TEXT,
            bank_name       TEXT,
            broker_code     TEXT,
            euin            TEXT,
            remarks         TEXT,
            sys_regn_date   TEXT,
            rep_date        TEXT,
            upload_batch    TEXT,
            UNIQUE(trxn_no, folio_no)
        );

        CREATE TABLE IF NOT EXISTS cams_sip (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            folio_no        TEXT,
            inv_name        TEXT,
            pan             TEXT,
            product         TEXT,
            scheme          TEXT,
            amc_code        TEXT,
            auto_trno       TEXT,
            request_ref_no  TEXT,
            auto_amount     REAL,
            from_date       TEXT,
            to_date         TEXT,
            cease_date      TEXT,
            periodicity     TEXT,
            period_day      INTEGER,
            payment_mode    TEXT,
            bank            TEXT,
            ac_type         TEXT,
            status          TEXT,
            euin            TEXT,
            broker_code     TEXT,
            reg_date        TEXT,
            remarks         TEXT,
            upload_batch    TEXT,
            UNIQUE(auto_trno, folio_no)
        );

        CREATE TABLE IF NOT EXISTS cams_aum (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            folio_no        TEXT,
            inv_name        TEXT,
            pan_no          TEXT,
            product         TEXT,
            sch_name        TEXT,
            amc_code        TEXT,
            clos_bal        REAL,
            rupee_bal       REAL,
            email           TEXT,
            rep_date        TEXT,
            upload_batch    TEXT,
            UNIQUE(folio_no, product, rep_date)
        );

        -- CAMS Brokerage (WBR77) - Raw file structure
        CREATE TABLE IF NOT EXISTS cams_brokerage (
            id                      INTEGER PRIMARY KEY AUTOINCREMENT,
            amc_code                TEXT,
            proc_date               TEXT,
            folio_no                TEXT,
            scheme_code             TEXT,
            trxn_type               TEXT,
            trxn_no                 TEXT,
            plot_amount             REAL,
            plot_units              REAL,
            post_date               TEXT,
            trade_date_time         TEXT,
            entry_date              TEXT,
            user_code               TEXT,
            user_trxnno             TEXT,
            trxn_nature             TEXT,
            ter_location            TEXT,
            sys_reg_date            TEXT,
            aut_txn_no              TEXT,
            auto_amount             REAL,
            aut_txn_type            TEXT,
            cease_date              TEXT,
            remed_date              TEXT,
            forf_date               TEXT,
            src_brk_code            TEXT,
            brok_code               TEXT,
            brh_code                TEXT,
            sub_brk_arn             TEXT,
            ae_code                 TEXT,
            arn_emp_code            TEXT,
            euin_opted              TEXT,
            euin_valid              TEXT,
            brk_comm_paid           TEXT,
            adj_flag                TEXT,
            brkage_type             TEXT,
            brkage_rate             REAL,
            total_upfront           REAL,
            defer_frequency         TEXT,
            defer_no_of_installment INTEGER,
            pay_installment_no      INTEGER,
            brkage_amt              REAL,
            brkage_from             TEXT,
            brkage_to               TEXT,
            proc_from_date          TEXT,
            proc_to_date            TEXT,
            trxn_desc               TEXT,
            spl_upf_tenure          INTEGER,
            upf_tenure_end_date     TEXT,
            brk_pay_dt              TEXT,
            clw_type                TEXT,
            clw_period              TEXT,
            rec_flag                TEXT,
            p_si_date               TEXT,
            rec_period              TEXT,
            clw_amt                 REAL,
            upf_paid                REAL,
            fee_id                  TEXT,
            am_code                 TEXT,
            am_comm                 REAL,
            am_rate                 REAL,
            avg_assets              REAL,
            cam_comm                REAL,
            cam_rate                REAL,
            mam_comm                REAL,
            mam_rate                REAL,
            no_of_days              INTEGER,
            orig_ae_code            TEXT,
            orig_brh_code           TEXT,
            orig_brk_code           TEXT,
            rate_ref_id             TEXT,
            ref_no                  TEXT,
            trxn_app_no             TEXT,
            txn_sch_code            TEXT,
            clw_prd                 TEXT,
            clw_required            TEXT,
            p_si_mis_code           TEXT,
            p_si_user_trxnno        TEXT,
            seq_no                  INTEGER,
            p_si_amt                REAL,
            p_si_tr_no              TEXT,
            p_si_type               TEXT,
            pur_si_units            REAL,
            remarks                 TEXT,
            to_scheme               TEXT,
            trxn_sign               TEXT,
            brk_posted              TEXT,
            inv_name                TEXT,
            brok_gst_state_code     TEXT,
            igst_rate               REAL,
            cgst_rate               REAL,
            sgst_rate               REAL,
            igst_value              REAL,
            cgst_value              REAL,
            sgst_value              REAL,
            location_code           TEXT,
            prev_folio              TEXT,
            brok_category           TEXT,
            p_scheme_code           TEXT,
            p_trxn_type             TEXT,
            p_trxn_no               TEXT,
            p_folio_no              TEXT,
            p_plot_amount           REAL,
            p_plot_units            REAL,
            folio_old               TEXT,
            scheme_folio_number     TEXT,
            amc_ref_no              TEXT,
            request_ref_no          TEXT,
            write_off_reason        TEXT,
            hold_reason             TEXT,
            brokerage_acrual_month  TEXT,
            prev_trxn_no            TEXT,
            prev_trxn_date          TEXT,
            upload_batch            TEXT,
            UNIQUE(trxn_no, folio_no, brokerage_acrual_month)
        );

        -- ── KFinTech ────────────────────────────────────────────────────────

        CREATE TABLE IF NOT EXISTS kfin_folio (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            folio_no        TEXT,
            inv_name        TEXT,
            pan_no          TEXT,
            fund_code       TEXT,
            product_code    TEXT,
            scheme_code     TEXT,
            div_opt         TEXT,
            fund_desc       TEXT,
            email           TEXT,
            mobile_no       TEXT,
            address1        TEXT,
            address2        TEXT,
            address3        TEXT,
            city            TEXT,
            pincode         TEXT,
            state           TEXT,
            country         TEXT,
            dob             TEXT,
            tax_status      TEXT,
            occupation_code TEXT,
            occ_desc        TEXT,
            holding_nature  TEXT,
            joint_name1     TEXT,
            joint_name2     TEXT,
            bank_accno      TEXT,
            bank_name       TEXT,
            ac_type         TEXT,
            bank_branch     TEXT,
            broker_code     TEXT,
            mapin_id        TEXT,
            rep_date        TEXT,
            upload_batch    TEXT,
            UNIQUE(folio_no, product_code)
        );

        CREATE TABLE IF NOT EXISTS kfin_transactions (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            fund_code       TEXT,
            product_code    TEXT,
            folio_no        TEXT,
            scheme_code     TEXT,
            div_opt         TEXT,
            fund_desc       TEXT,
            inv_name        TEXT,
            pan             TEXT,
            trxn_no         TEXT,
            trxn_type       TEXT,
            trxn_mode       TEXT,
            trxn_status     TEXT,
            trxn_desc       TEXT,
            trxn_subtype    TEXT,
            trade_date      TEXT,
            post_date       TEXT,
            nav             REAL,
            units           REAL,
            amount          REAL,
            stt             REAL DEFAULT 0,
            sip_reg_no      TEXT,
            sip_reg_date    TEXT,
            ih_no           TEXT,
            chq_bank        TEXT,
            ac_no           TEXT,
            agent_code      TEXT,
            branch          TEXT,
            inward_no       TEXT,
            remarks         TEXT,
            rep_date        TEXT,
            upload_batch    TEXT,
            UNIQUE(trxn_no, folio_no)
        );

        CREATE TABLE IF NOT EXISTS kfin_sip (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            folio_no            TEXT,
            inv_name            TEXT,
            pan                 TEXT,
            fund_code           TEXT,
            product_code        TEXT,
            scheme_code         TEXT,
            scheme_name         TEXT,
            reg_sl_no           TEXT,
            ih_no               TEXT,
            amount              REAL,
            start_date          TEXT,
            end_date            TEXT,
            no_of_installments  INTEGER,
            frequency           TEXT,
            sip_type            TEXT,
            sip_mode            TEXT,
            terminate_date      TEXT,
            status              TEXT,
            ecs_bank            TEXT,
            ecs_ac_no           TEXT,
            agent_code          TEXT,
            agent_name          TEXT,
            reg_date            TEXT,
            zone                TEXT,
            branch              TEXT,
            upload_batch        TEXT,
            UNIQUE(reg_sl_no, folio_no)
        );

        CREATE TABLE IF NOT EXISTS kfin_aum (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            folio_no        TEXT,
            inv_name        TEXT,
            fund_code       TEXT,
            product_code    TEXT,
            scheme_code     TEXT,
            div_opt         TEXT,
            fund_desc       TEXT,
            email           TEXT,
            balance         REAL,
            aum             REAL,
            nav             REAL,
            rep_date        TEXT,
            upload_batch    TEXT,
            UNIQUE(folio_no, product_code, rep_date)
        );

        -- KFinTech Brokerage (MFSD205) - Raw file structure
        CREATE TABLE IF NOT EXISTS kfin_brokerage (
            id                      INTEGER PRIMARY KEY AUTOINCREMENT,
            product_code            TEXT,
            fund_description        TEXT,
            fund                    TEXT,
            scheme                  TEXT,
            plan                    TEXT,
            option                  TEXT,
            account_number          TEXT,
            application_number      TEXT,
            investor_name           TEXT,
            address_1               TEXT,
            address_2               TEXT,
            address_3               TEXT,
            city                    TEXT,
            pincode                 TEXT,
            transaction_description TEXT,
            from_date               TEXT,
            to_date                 TEXT,
            amount                  REAL,
            units                   REAL,
            transaction_date        TEXT,
            process_date            TEXT,
            percentage              REAL,
            brokerage               REAL,
            sub_broker              TEXT,
            account_type            TEXT,
            brokerage_head          TEXT,
            brokerage_type          TEXT,
            transaction_number      TEXT,
            branch_code             TEXT,
            cheque_number           TEXT,
            starting_date           TEXT,
            ending_date             TEXT,
            warrant_number          TEXT,
            warrant_date            TEXT,
            daily_product           REAL,
            cumulative_nav          REAL,
            average_assets          REAL,
            transaction_id          TEXT,
            scheme_code             TEXT,
            transaction_head        TEXT,
            fee_type                TEXT,
            adjustment_flag         TEXT,
            switch_flag             TEXT,
            gross_brokerage         REAL,
            stt_amount              REAL,
            educess_amount          REAL,
            tran_type_code          TEXT,
            upload_batch            TEXT,
            UNIQUE(transaction_id)
        );

        -- ── Manual / Config ─────────────────────────────────────────────────

        CREATE TABLE IF NOT EXISTS monthly_brokerage (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            amc         TEXT,
            month       TEXT,
            year        INTEGER,
            amount      REAL,
            notes       TEXT,
            timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(amc, month, year)
        );

        CREATE TABLE IF NOT EXISTS amc_code_map (
            amc_code    TEXT PRIMARY KEY,
            amc_name    TEXT NOT NULL
        );
        """)
