"""New Structure """

import sqlite3
from contextlib import contextmanager

# DB_PATH = "mfd_local.db"

import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mfd_local.db")


@contextmanager
def get_conn():
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db() -> None:
    with get_conn() as conn:
        conn.executescript("""
        PRAGMA journal_mode = WAL;
        PRAGMA foreign_keys = ON;

        -- =====================================================================
        -- BSE CLIENT MASTER  (exact header order)
        -- =====================================================================
    CREATE TABLE IF NOT EXISTS bse_client_master (
        member_code                 TEXT,
        client_code                 TEXT PRIMARY KEY,
        primary_holder_first_name   TEXT,
        primary_holder_middle_name  TEXT,
        primary_holder_last_name    TEXT,
        tax_status                  TEXT,
        gender                      TEXT,
        primary_holder_dob_incorporation          TEXT,
        occupation_code             TEXT,
        holding_nature              TEXT,
        second_holder_first_name    TEXT,
        second_holder_middle_name   TEXT,
        second_holder_last_name     TEXT,
        third_holder_first_name     TEXT,
        third_holder_middle_name    TEXT,
        third_holder_last_name      TEXT,
        second_holder_dob           TEXT,
        third_holder_dob            TEXT,
        guardian_first_name         TEXT,
        guardian_middle_name        TEXT,
        guardian_last_name          TEXT,
        guardian_dob                TEXT,
        primary_holder_pan_exempt   TEXT,
        second_holder_pan_exempt    TEXT,
        third_holder_pan_exempt     TEXT,
        guardian_pan_exempt         TEXT,
        primary_holder_pan          TEXT,
        second_holder_pan           TEXT,
        third_holder_pan            TEXT,
        guardian_pan                TEXT,
        primary_holder_exempt_category   TEXT,
        second_holder_exempt_category    TEXT,
        third_holder_exempt_category     TEXT,
        guardian_exempt_category         TEXT,
        client_type                 TEXT,
        pms                         TEXT,
        default_dp                  TEXT,
        cdsl_dpid                   TEXT,
        cdsl_cltid                  TEXT,
        cmbp_id                     TEXT,
        nsdl_dpid                   TEXT,
        nsdl_cltid                  TEXT,
        -- Bank 1
        account_type_1              TEXT,
        account_no_1                TEXT,
        micr_no_1                   TEXT,
        ifsc_code_1                 TEXT,
        bank_name_1                 TEXT,
        bank_branch_1               TEXT,
        default_bank_flag_1         TEXT,
        bank1_created_at            TEXT,
        bank1_last_modified_at      TEXT,
        bank1_status                TEXT,
        -- Bank 2
        account_type_2              TEXT,
        account_no_2                TEXT,
        micr_no_2                   TEXT,
        ifsc_code_2                 TEXT,
        bank_name_2                 TEXT,
        bank_branch_2               TEXT,
        default_bank_flag_2         TEXT,
        bank2_created_at            TEXT,
        bank2_last_modified_at      TEXT,
        bank2_status                TEXT,
        -- Bank 3
        account_type_3              TEXT,
        account_no_3                TEXT,
        micr_no_3                   TEXT,
        ifsc_code_3                 TEXT,
        bank_name_3                 TEXT,
        bank_branch_3               TEXT,
        default_bank_flag_3         TEXT,
        bank3_created_at            TEXT,
        bank3_last_modified_at      TEXT,
        bank3_status                TEXT,
        -- Bank 4
        account_type_4              TEXT,
        account_no_4                TEXT,
        micr_no_4                   TEXT,
        ifsc_code_4                 TEXT,
        bank_name_4                 TEXT,
        bank_branch_4               TEXT,
        default_bank_flag_4         TEXT,
        bank4_created_at            TEXT,
        bank4_last_modified_at      TEXT,
        bank4_status                TEXT,
        -- Bank 5
        account_type_5              TEXT,
        account_no_5                TEXT,
        micr_no_5                   TEXT,
        ifsc_code_5                 TEXT,
        bank_name_5                 TEXT,
        bank_branch_5               TEXT,
        default_bank_flag_5         TEXT,
        bank5_created_at            TEXT,
        bank5_last_modified_at      TEXT,
        bank5_status                TEXT,
        -- Contact / Address
        cheque_name                 TEXT,
        div_pay_mode                TEXT,
        address1                    TEXT,
        address2                    TEXT,
        address3                    TEXT,
        city                        TEXT,
        state                       TEXT,
        pincode                     TEXT,
        country                     TEXT,
        resi_phone                  TEXT,
        resi_fax                    TEXT,
        office_phone                TEXT,
        office_fax                  TEXT,
        email                       TEXT,
        communication_mode          TEXT,
        -- Foreign address
        foreign_address1            TEXT,
        foreign_address2            TEXT,
        foreign_address3            TEXT,
        foreign_city                TEXT,
        foreign_pincode             TEXT,
        foreign_state               TEXT,
        foreign_country             TEXT,
        foreign_resi_phone          TEXT,
        foreign_resi_fax            TEXT,
        foreign_off_phone           TEXT,
        foreign_off_fax             TEXT,
        indian_mobile_no            TEXT,
        -- KYC
        primary_holder_kyc_type     TEXT,
        primary_holder_ckyc_no      TEXT,
        second_holder_kyc_type      TEXT,
        second_holder_ckyc_no       TEXT,
        third_holder_kyc_type       TEXT,
        third_holder_ckyc_no        TEXT,
        guardian_kyc_type           TEXT,
        guardian_ckyc_no            TEXT,
        primary_holder_kra_exempt   TEXT,
        second_holder_kra_exempt    TEXT,
        third_holder_kra_exempt     TEXT,
        guardian_kra_exempt         TEXT,
        aadhaar_updated             TEXT,
        mapin_id                    TEXT,
        paperless_flag              TEXT,
        lei_no                      TEXT,
        lei_validity                TEXT,
        email_declaration_flag      TEXT,
        mobile_declaration_flag     TEXT,
        branch                      TEXT,
        dealer                      TEXT,
        -- Nomination
        nomination_opt              TEXT,
        nomination_auth_mode        TEXT,
        nominee1_name               TEXT,
        nominee1_relationship       TEXT,
        nominee1_applicable_pct     REAL,
        nominee1_minor_flag         TEXT,
        nominee1_dob                TEXT,
        nominee1_guardian           TEXT,
        nominee1_guardian_pan       TEXT,
        nom1_id_typ                 TEXT,
        nom1_idno                   TEXT,
        nom1_email                  TEXT,
        nom1_mob                    TEXT,
        nom1_add1                   TEXT,
        nom1_add2                   TEXT,
        nom1_add3                   TEXT,
        nom1_city                   TEXT,
        nom1_pin                    TEXT,
        nom1_con                    TEXT,
        nominee2_name               TEXT,
        nominee2_relationship       TEXT,
        nominee2_applicable_pct     REAL,
        nominee2_dob                TEXT,
        nominee2_minor_flag         TEXT,
        nominee2_guardian           TEXT,
        nominee2_guardian_pan       TEXT,
        nom2_id_typ                 TEXT,
        nom2_idno                   TEXT,
        nom2_email                  TEXT,
        nom2_mob                    TEXT,
        nom2_add1                   TEXT,
        nom2_add2                   TEXT,
        nom2_add3                   TEXT,
        nom2_city                   TEXT,
        nom2_pin                    TEXT,
        nom2_con                    TEXT,
        nominee3_name               TEXT,
        nominee3_relationship       TEXT,
        nominee3_applicable_pct     REAL,
        nominee3_dob                TEXT,
        nominee3_minor_flag         TEXT,
        nominee3_guardian           TEXT,
        nominee3_guardian_pan       TEXT,
        nom3_id_typ                 TEXT,
        nom3_idno                   TEXT,
        nom3_email                  TEXT,
        nom3_mob                    TEXT,
        nom3_add1                   TEXT,
        nom3_add2                   TEXT,
        nom3_add3                   TEXT,
        nom3_city                   TEXT,
        nom3_pin                    TEXT,
        nom3_con                    TEXT,
        nom_soa                     TEXT,
        -- Second / Third holder extras
        second_holder_email                 TEXT,
        second_holder_email_declaration     TEXT,
        second_holder_mobile                TEXT,
        second_holder_mobile_declaration    TEXT,
        third_holder_email                  TEXT,
        third_holder_email_declaration      TEXT,
        third_holder_mobile                 TEXT,
        third_holder_mobile_declaration     TEXT,
        nomination_flag                     TEXT,
        nomination_auth_date                TEXT,
        guardian_relationship               TEXT,
        created_by                          TEXT,
        created_at                          TEXT,
        last_modified_by                    TEXT,
        last_modified_at                    TEXT,
        upload_batch                        TEXT
    );

    CREATE TABLE IF NOT EXISTS bse_sip (
        status                  TEXT,
        member_code             TEXT,
        client_code             TEXT,
        client_name             TEXT,
        pg_bank_reference_no    TEXT,
        xsip_regn_no            TEXT PRIMARY KEY,
        regn_date               TEXT,
        amc_name                TEXT,
        rta_scheme_code         TEXT,
        scheme_name             TEXT,
        frequency_type          TEXT,
        start_date              TEXT,
        end_date                TEXT,
        installments_amt        REAL,
        brokerage               REAL,
        entry_by                TEXT,
        mandate_id              TEXT,
        dpc_flag                TEXT,
        dp_trans                TEXT,
        sub_broker              TEXT,
        euin                    TEXT,
        euin_decl               TEXT,
        first_order             TEXT,
        folio_no                TEXT,
        remarks                 TEXT,
        sub_broker_arncode      TEXT,
        no_of_installments      INTEGER,
        exchange_remark         TEXT,
        health_declaration_flag TEXT,
        nominee_dob             TEXT,
        disclaimer_flag         TEXT,
        internal_ref_no         TEXT,
        primary_holder_email    TEXT,
        primary_holder_mobile   TEXT,
        second_holder_email     TEXT,
        second_holder_mobile    TEXT,
        third_holder_email      TEXT,
        third_holder_mobile     TEXT,
        upload_batch            TEXT
    
    );
    
    -- =====================================================================
    -- BSE SCHEME MASTER  (exact header order)
    -- =====================================================================

    CREATE TABLE IF NOT EXISTS bse_scheme_master (
        id                              INTEGER PRIMARY KEY AUTOINCREMENT,
        unique_no                       TEXT,
        scheme_code                     TEXT,
        rta_scheme_code                 TEXT,
        amc_scheme_code                 TEXT,
        isin                            TEXT,
        amc_code                        TEXT,
        scheme_type                     TEXT,
        scheme_plan                     TEXT,
        scheme_name                     TEXT,
        purchase_allowed                TEXT,
        purchase_transaction_mode       TEXT,
        min_purchase_amount             REAL,
        additional_purchase_amount      REAL,
        max_purchase_amount             REAL,
        purchase_amount_multiplier      REAL,
        purchase_cutoff_time            TEXT,
        redemption_allowed              TEXT,
        redemption_transaction_mode     TEXT,
        min_redemption_qty              REAL,
        redemption_qty_multiplier       REAL,
        max_redemption_qty              REAL,
        redemption_amount_min           REAL,
        redemption_amount_max           REAL,
        redemption_amount_multiple      REAL,
        redemption_cutoff_time          TEXT,
        rta_agent_code                  TEXT,
        amc_active_flag                 TEXT,
        dividend_reinvestment_flag      TEXT,
        sip_flag                        TEXT,
        stp_flag                        TEXT,
        swp_flag                        TEXT,
        switch_flag                     TEXT,
        settlement_type                 TEXT,
        amc_ind                         TEXT,
        face_value                      REAL,
        start_date                      TEXT,
        end_date                        TEXT,
        exit_load_flag                  TEXT,
        exit_load                       TEXT,
        lock_in_period_flag             TEXT,
        lock_in_period                  TEXT,
        channel_partner_code            TEXT,
        reopening_date                  TEXT,
        upload_batch                    TEXT,
        UNIQUE(scheme_code, rta_scheme_code)
    );
    
    CREATE INDEX IF NOT EXISTS idx_bsm_scheme_code ON bse_scheme_master(scheme_code);
    CREATE INDEX IF NOT EXISTS idx_bsm_rta_scheme_code ON bse_scheme_master(rta_scheme_code);
    CREATE INDEX IF NOT EXISTS idx_bsm_isin ON bse_scheme_master(isin);

    -- ─────────────────────────────────────────────
    -- CAMS TABLES
    -- ─────────────────────────────────────────────

    CREATE TABLE IF NOT EXISTS cams_wbr4_aum (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        foliochk            TEXT,
        inv_name            TEXT,
        address1            TEXT,
        address2            TEXT,
        address3            TEXT,
        city                TEXT,
        pincode             TEXT,
        product             TEXT,
        sch_name            TEXT,
        rep_date            TEXT,
        clos_bal            REAL,
        rupee_bal           REAL,
        subbrok             TEXT,
        reinv_flag          TEXT,
        joint1_name         TEXT,
        joint2_name         TEXT,
        phone_off           TEXT,
        phone_res           TEXT,
        email               TEXT,
        holding_nature      TEXT,
        uin_no              TEXT,
        broker_code         TEXT,
        pan_no              TEXT,
        joint1_pan          TEXT,
        joint2_pan          TEXT,
        guard_pan           TEXT,
        tax_status          TEXT,
        inv_iin             TEXT,
        altfolio            TEXT,
        euin                TEXT,
        exchange_flag       TEXT,
        tpa_linked          TEXT,
        fh_ckyc_no          TEXT,
        jh1_ckyc            TEXT,
        jh2_ckyc            TEXT,
        g_ckyc_no           TEXT,
        jh1_dob             TEXT,
        jh2_dob             TEXT,
        guardian_dob        TEXT,
        amc_code            TEXT,
        gst_state_code      TEXT,
        folio_old           TEXT,
        scheme_folio_number TEXT,
        country             TEXT,
        upload_batch            TEXT,
        UNIQUE(foliochk, product, rep_date, amc_code)
    );

    CREATE TABLE IF NOT EXISTS cams_wbr9_folio (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        foliochk            TEXT,
        inv_name            TEXT,
        address1            TEXT,
        address2            TEXT,
        address3            TEXT,
        city                TEXT,
        pincode             TEXT,
        product             TEXT,
        sch_name            TEXT,
        rep_date            TEXT,
        clos_bal            REAL,
        rupee_bal           REAL,
        jnt_name1           TEXT,
        jnt_name2           TEXT,
        phone_off           TEXT,
        phone_res           TEXT,
        email               TEXT,
        holding_nature      TEXT,
        uin_no              TEXT,
        pan_no              TEXT,
        joint1_pan          TEXT,
        joint2_pan          TEXT,
        guard_pan           TEXT,
        tax_status          TEXT,
        broker_code         TEXT,
        subbroker           TEXT,
        reinv_flag          TEXT,
        bank_name           TEXT,
        branch              TEXT,
        ac_type             TEXT,
        ac_no               TEXT,
        b_address1          TEXT,
        b_address2          TEXT,
        b_address3          TEXT,
        b_city              TEXT,
        b_pincode           TEXT,
        inv_dob             TEXT,
        mobile_no           TEXT,
        occupation          TEXT,
        inv_iin             TEXT,
        nom_name            TEXT,
        relation            TEXT,
        nom_addr1           TEXT,
        nom_addr2           TEXT,
        nom_addr3           TEXT,
        nom_city            TEXT,
        nom_state           TEXT,
        nom_pincode         TEXT,
        nom_ph_off          TEXT,
        nom_ph_res          TEXT,
        nom_email           TEXT,
        nom_percentage      REAL,
        nom2_name           TEXT,
        nom2_relation       TEXT,
        nom2_addr1          TEXT,
        nom2_addr2          TEXT,
        nom2_addr3          TEXT,
        nom2_city           TEXT,
        nom2_state          TEXT,
        nom2_pincode        TEXT,
        nom2_ph_off         TEXT,
        nom2_ph_res         TEXT,
        nom2_email          TEXT,
        nom2_percentage     REAL,
        nom3_name           TEXT,
        nom3_relation       TEXT,
        nom3_addr1          TEXT,
        nom3_addr2          TEXT,
        nom3_addr3          TEXT,
        nom3_city           TEXT,
        nom3_state          TEXT,
        nom3_pincode        TEXT,
        nom3_ph_off         TEXT,
        nom3_ph_res         TEXT,
        nom3_email          TEXT,
        nom3_percentage     REAL,
        ifsc_code           TEXT,
        dp_id               TEXT,
        demat               TEXT,
        guard_name          TEXT,
        brokcode            TEXT,
        folio_date          TEXT,
        aadhaar             TEXT,
        tpa_linked          TEXT,
        fh_ckyc_no          TEXT,
        jh1_ckyc            TEXT,
        jh2_ckyc            TEXT,
        g_ckyc_no           TEXT,
        jh1_dob             TEXT,
        jh2_dob             TEXT,
        guardian_dob        TEXT,
        amc_code            TEXT,
        gst_state_code      TEXT,
        folio_old           TEXT,
        scheme_folio_number TEXT,
        country             TEXT,
        remarks             TEXT,
        jh1_email           TEXT,
        jh2_email           TEXT,
        jh1_mobile_no       TEXT,
        jh2_mobile_no       TEXT,
        upload_batch            TEXT,
        UNIQUE(foliochk, product, amc_code)
    );

    CREATE TABLE IF NOT EXISTS cams_wbr2_transaction (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        amc_code            TEXT,
        folio_no            TEXT,
        prodcode            TEXT,
        scheme              TEXT,
        inv_name            TEXT,
        trxntype            TEXT,
        trxnno              TEXT,
        trxnmode            TEXT,
        trxnstat            TEXT,
        usercode            TEXT,
        usrtrxno            TEXT,
        traddate            TEXT,
        postdate            TEXT,
        purprice            REAL,
        units               REAL,
        amount              REAL,
        brokcode            TEXT,
        subbrok             TEXT,
        brokperc            REAL,
        brokcomm            REAL,
        altfolio            TEXT,
        rep_date            TEXT,
        time1               TEXT,
        trxnsubtyp          TEXT,
        application_no      TEXT,
        trxn_nature         TEXT,
        tax                 REAL,
        total_tax           REAL,
        te_15h              TEXT,
        micr_no             TEXT,
        remarks             TEXT,
        swflag              TEXT,
        old_folio           TEXT,
        seq_no              TEXT,
        reinvest_flag       TEXT,
        mult_brok           TEXT,
        stt                 REAL,
        location            TEXT,
        scheme_type         TEXT,
        tax_status          TEXT,
        load                REAL,
        scanrefno           TEXT,
        pan                 TEXT,
        inv_iin             TEXT,
        targ_src_scheme     TEXT,
        trxn_type_flag      TEXT,
        ticob_trtype        TEXT,
        ticob_trno          TEXT,
        ticob_posted_date   TEXT,
        dp_id               TEXT,
        trxn_charges        REAL,
        eligib_amt          REAL,
        src_of_txn          TEXT,
        trxn_suffix         TEXT,
        siptrxnno           TEXT,
        ter_location        TEXT,
        euin                TEXT,
        euin_valid          TEXT,
        euin_opted          TEXT,
        sub_brk_arn         TEXT,
        exch_dc_flag        TEXT,
        src_brk_code        TEXT,
        sys_regn_date       TEXT,
        ac_no               TEXT,
        bank_name           TEXT,
        reversal_code       TEXT,
        exchange_flag       TEXT,
        ca_initiated_date   TEXT,
        gst_state_code      TEXT,
        igst_amount         REAL,
        cgst_amount         REAL,
        sgst_amount         REAL,
        rev_remark          TEXT,
        original_trxnno     TEXT,
        stamp_duty          REAL,
        folio_old           TEXT,
        scheme_folio_number TEXT,
        amc_ref_no          TEXT,
        request_ref_no      TEXT,
        transmission_flag   TEXT,
        upload_batch            TEXT,
        UNIQUE(trxnno, folio_no)
    );

    CREATE TABLE IF NOT EXISTS cams_wbr49_sip (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        product             TEXT,
        scheme              TEXT,
        folio_no            TEXT,
        inv_name            TEXT,
        aut_trntyp          TEXT,
        auto_trno           TEXT,
        auto_amount         REAL,
        from_date           TEXT,
        to_date             TEXT,
        cease_date          TEXT,
        periodicity         TEXT,
        period_day          TEXT,
        inv_iin             TEXT,
        payment_mode        TEXT,
        target_scheme       TEXT,
        reg_date            TEXT,
        subbroker           TEXT,
        remarks             TEXT,
        top_up_frq          TEXT,
        top_up_amt          REAL,
        ac_type             TEXT,
        bank                TEXT,
        branch              TEXT,
        instrm_no           TEXT,
        cheq_micr_no        TEXT,
        ac_holder_name      TEXT,
        pan                 TEXT,
        top_up_perc         REAL,
        euin                TEXT,
        sub_arn_code        TEXT,
        ter_location        TEXT,
        scheme_code         TEXT,
        target_scheme_code  TEXT,
        amc_code            TEXT,
        user_code           TEXT,
        package_name        TEXT,
        special_product     TEXT,
        subtrxndesc         TEXT,
        pause_from_date     TEXT,
        pause_to_date       TEXT,
        folio_old           TEXT,
        ft_sip_regno        TEXT,
        scheme_folio_number TEXT,
        request_ref_no      TEXT,
        upload_batch            TEXT,
        UNIQUE(auto_trno, folio_no)
    );

    CREATE TABLE IF NOT EXISTS cams_wbr77_brokerage (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        amc_code                    TEXT,
        proc_date                   TEXT,
        folio_no                    TEXT,
        scheme_code                 TEXT,
        trxn_type                   TEXT,
        trxn_no                     TEXT,
        plot_amount                 REAL,
        plot_units                  REAL,
        post_date                   TEXT,
        trade_date_time             TEXT,
        entry_date                  TEXT,
        user_code                   TEXT,
        user_trxnno                 TEXT,
        trxn_nature                 TEXT,
        ter_location                TEXT,
        sys_reg_date                TEXT,
        aut_txn_no                  TEXT,
        auto_amount                 REAL,
        aut_txn_type                TEXT,
        cease_date                  TEXT,
        remed_date                  TEXT,
        forf_date                   TEXT,
        src_brk_code                TEXT,
        brok_code                   TEXT,
        brh_code                    TEXT,
        sub_brk_arn                 TEXT,
        ae_code                     TEXT,
        arn_emp_code                TEXT,
        euin_opted                  TEXT,
        euin_valid                  TEXT,
        brk_comm_paid               REAL,
        adj_flag                    TEXT,
        brkage_type                 TEXT,
        brkage_rate                 REAL,
        total_upfront               REAL,
        defer_frequency             TEXT,
        defer_no_of_installment     INTEGER,
        pay_installment_no          INTEGER,
        brkage_amt                  REAL,
        brkage_from                 TEXT,
        brkage_to                   TEXT,
        proc_from_date              TEXT,
        proc_to_date                TEXT,
        trxn_desc                   TEXT,
        spl_upf_tenure              TEXT,
        upf_tenure_end_date         TEXT,
        brk_pay_dt                  TEXT,
        clw_type                    TEXT,
        clw_period                  TEXT,
        rec_flag                    TEXT,
        p_si_date                   TEXT,
        rec_period                  TEXT,
        clw_amt                     REAL,
        upf_paid                    REAL,
        fee_id                      TEXT,
        am_code                     TEXT,
        am_comm                     REAL,
        am_rate                     REAL,
        avg_assets                  REAL,
        cam_comm                    REAL,
        cam_rate                    REAL,
        mam_comm                    REAL,
        mam_rate                    REAL,
        no_of_days                  INTEGER,
        orig_ae_code                TEXT,
        orig_brh_code               TEXT,
        orig_brk_code               TEXT,
        rate_ref_id                 TEXT,
        ref_no                      TEXT,
        trxn_app_no                 TEXT,
        txn_sch_code                TEXT,
        clw_prd                     TEXT,
        clw_required                TEXT,
        p_si_mis_code               TEXT,
        p_si_user_trxnno            TEXT,
        seq_no                      TEXT,
        p_si_amt                    REAL,
        p_si_tr_no                  TEXT,
        p_si_type                   TEXT,
        pur_si_units                REAL,
        remarks                     TEXT,
        to_scheme                   TEXT,
        trxn_sign                   TEXT,
        brk_posted                  TEXT,
        inv_name                    TEXT,
        brok_gst_state_code         TEXT,
        igst_rate                   REAL,
        cgst_rate                   REAL,
        sgst_rate                   REAL,
        igst_value                  REAL,
        cgst_value                  REAL,
        sgst_value                  REAL,
        location_code               TEXT,
        prev_folio                  TEXT,
        brok_category               TEXT,
        p_scheme_code               TEXT,
        p_trxn_type                 TEXT,
        p_trxn_no                   TEXT,
        p_folio_no                  TEXT,
        p_plot_amount               REAL,
        p_plot_units                REAL,
        folio_old                   TEXT,
        scheme_folio_number         TEXT,
        amc_ref_no                  TEXT,
        request_ref_no              TEXT,
        write_off_reason            TEXT,
        hold_reason                 TEXT,
        brokerage_accrual_month     TEXT,
        prev_trxn_no                TEXT,
        prev_trxn_date              TEXT,
        imported_at                 TEXT DEFAULT (datetime('now')),
        upload_batch                    TEXT,
        UNIQUE(trxn_no, folio_no, brokerage_accrual_month)
    );

    -- ─────────────────────────────────────────────
    -- KFINTECH TABLES
    -- ─────────────────────────────────────────────

    CREATE TABLE IF NOT EXISTS kfin_mfsd203_aum (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        product_code        TEXT,
        fund                TEXT,
        folio_number        TEXT,
        scheme_code         TEXT,
        dividend_option     TEXT,
        fund_description    TEXT,
        balance             REAL,
        pledged             REAL,
        transaction_date    TEXT,
        transaction_type    TEXT,
        hold_mode           TEXT,
        agent_code          TEXT,
        broker_code         TEXT,
        p_out_code          TEXT,
        investor_id         TEXT,
        investor_name       TEXT,
        address1            TEXT,
        address2            TEXT,
        address3            TEXT,
        city                TEXT,
        pincode             TEXT,
        phone_residence     TEXT,
        phone_office        TEXT,
        fax                 TEXT,
        email               TEXT,
        aum                 REAL,
        nav                 REAL,
        report_date         TEXT,
        report_time         TEXT,
        to_date             TEXT,
        upload_batch            TEXT,
        UNIQUE(folio_number, product_code, scheme_code, report_date)
    );

    CREATE TABLE IF NOT EXISTS kfin_mfsd211_folio (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        product_code                TEXT,
        fund                        TEXT,
        folio                       TEXT,
        dividend_option             TEXT,
        fund_description            TEXT,
        investor_name               TEXT,
        joint_name1                 TEXT,
        joint_name2                 TEXT,
        address1                    TEXT,
        address2                    TEXT,
        address3                    TEXT,
        city                        TEXT,
        pincode                     TEXT,
        state                       TEXT,
        country                     TEXT,
        tpin                        TEXT,
        date_of_birth               TEXT,
        f_name                      TEXT,
        m_name                      TEXT,
        phone_residence             TEXT,
        phone_res1                  TEXT,
        phone_res2                  TEXT,
        phone_office                TEXT,
        phone_off1                  TEXT,
        phone_off2                  TEXT,
        fax_residence               TEXT,
        fax_office                  TEXT,
        tax_status                  TEXT,
        occ_code                    TEXT,
        email                       TEXT,
        bank_accno                  TEXT,
        bank_name                   TEXT,
        account_type                TEXT,
        branch                      TEXT,
        bank_address1               TEXT,
        bank_address2               TEXT,
        bank_address3               TEXT,
        bank_city                   TEXT,
        bank_phone                  TEXT,
        bank_state                  TEXT,
        bank_country                TEXT,
        investor_id                 TEXT,
        broker_code                 TEXT,
        pan_number                  TEXT,
        mobile_number               TEXT,
        report_date                 TEXT,
        report_time                 TEXT,
        occupation_description      TEXT,
        mode_of_holding             TEXT,
        mode_of_holding_description TEXT,
        mapin_id                    TEXT,
        holder1_aadhaar             TEXT,
        holder2_aadhaar             TEXT,
        holder3_aadhaar             TEXT,
        guardian_aadhaar            TEXT,
        imported_at                 TEXT DEFAULT (datetime('now')),
        UNIQUE(folio,fund,  product_code)
    );

    CREATE TABLE IF NOT EXISTS kfin_mfsd201_transaction (
        id                  INTEGER PRIMARY KEY AUTOINCREMENT,
        fmcode              TEXT,
        td_fund             TEXT,
        td_acno             TEXT,
        schpln              TEXT,
        divopt              TEXT,
        funddesc            TEXT,
        td_purred           TEXT,
        td_trno             TEXT,
        smcode              TEXT,
        chqno               TEXT,
        invname             TEXT,
        trnmode             TEXT,
        trnstat             TEXT,
        td_branch           TEXT,
        isctrno             TEXT,
        td_trdt             TEXT,
        td_prdt             TEXT,
        td_pop              REAL,
        loadper             REAL,
        td_units            REAL,
        td_amt              REAL,
        load1               REAL,
        td_agent            TEXT,
        td_broker           TEXT,
        brokper             REAL,
        brokcomm            REAL,
        invid               TEXT,
        crdate              TEXT,
        crtime              TEXT,
        trnsub              TEXT,
        td_appno            TEXT,
        unqno               TEXT,
        trdesc              TEXT,
        td_trtype           TEXT,
        purdate             TEXT,
        puramt              REAL,
        purunits            REAL,
        trflag              TEXT,
        sfunddt             TEXT,
        chqdate             TEXT,
        chqbank             TEXT,
        td_nav              REAL,
        td_ptrno            TEXT,
        stt                 REAL,
        ihno                TEXT,
        branchcode          TEXT,
        inwardno            TEXT,
        nctremarks          TEXT,
        pan1                TEXT,
        trcharges           REAL,
        sipregdt            TEXT,
        sipregslno          TEXT,
        divper              REAL,
        guardpanno          TEXT,
        can                 TEXT,
        exchorgtrtype       TEXT,
        elecTrxnflag        TEXT,
        cleared             TEXT,
        invstate            TEXT,
        
        UNIQUE(td_acno, td_trno, td_fund)
    );

    CREATE TABLE IF NOT EXISTS kfin_mfsd243_sip (
        id                      INTEGER PRIMARY KEY AUTOINCREMENT,
        zone                    TEXT,
        branch                  TEXT,
        location                TEXT,
        ihno                    TEXT,
        folio                   TEXT,
        investor_name           TEXT,
        registration_date       TEXT,
        start_date              TEXT,
        end_date                TEXT,
        no_of_installments      INTEGER,
        amount                  REAL,
        scheme                  TEXT,
        plan                    TEXT,
        agent_code              TEXT,
        agent_name              TEXT,
        subbroker               TEXT,
        scheme_name             TEXT,
        pan                     TEXT,
        sip_type                TEXT,
        sip_mode                TEXT,
        fund_code               TEXT,
        product_code            TEXT,
        frequency               TEXT,
        trtype                  TEXT,
        to_scheme               TEXT,
        to_plan                 TEXT,
        terminate_date          TEXT,
        status                  TEXT,
        to_product_code         TEXT,
        to_scheme_name          TEXT,
        ecsno                   TEXT,
        ecs_bank_name           TEXT,
        ecs_acno                TEXT,
        ecs_holder_name         TEXT,
        reg_slno                TEXT,
        inv_dp_id               TEXT,
        inv_client_id           TEXT,
        dp_inv_name             TEXT,
        modify_flag             TEXT,
        umrncode                TEXT,
        imported_at             TEXT DEFAULT (datetime('now')),
        UNIQUE(reg_slno, folio, scheme)
    );

    CREATE TABLE IF NOT EXISTS kfin_mfsd205_brokerage (
        id                      INTEGER PRIMARY KEY AUTOINCREMENT,
        product_code            TEXT,
        fund_description        TEXT,
        fund                    TEXT,
        scheme                  TEXT,
        plan                    TEXT,
        option                  TEXT,
        account_number          TEXT,
        application_number      TEXT,
        investor_name           TEXT,
        address1                TEXT,
        address2                TEXT,
        address3                TEXT,
        city                    TEXT,
        pincode                 TEXT,
        transaction_description TEXT,
        from_date               TEXT,
        to_date                 TEXT,
        amount                  REAL,
        units                   REAL,
        transaction_date        TEXT,
        process_date            TEXT,
        percentage              REAL,
        brokerage               REAL,
        sub_broker              TEXT,
        account_type            TEXT,
        brokerage_head          TEXT,
        brokerage_type          TEXT,
        transaction_number      TEXT,
        branch_code             TEXT,
        cheque_number           TEXT,
        starting_date           TEXT,
        ending_date             TEXT,
        warrant_number          TEXT,
        warrant_date            TEXT,
        daily_product           REAL,
        cumulative_nav          REAL,
        average_assets          REAL,
        transaction_id          TEXT,
        scheme_code             TEXT,
        transaction_head        TEXT,
        fee_type                TEXT,
        adjustment_flag         TEXT,
        switch_flag             TEXT,
        gross_brokerage         REAL,
        stt_amount              REAL,
        educcess_amount         REAL,
        tran_type_code          TEXT,
        imported_at             TEXT DEFAULT (datetime('now')),
        UNIQUE(transaction_number, account_number, fund, process_date)
    );
    
    -- =====================================================================
    -- MANUAL / CONFIG TABLES
    -- =====================================================================
    CREATE TABLE IF NOT EXISTS monthly_brokerage (
        id          INTEGER PRIMARY KEY AUTOINCREMENT,
        amc         TEXT,
        month       TEXT,
        year        INTEGER,
        amount      REAL,
        notes       TEXT,
        timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(amc, month, year)
    );

    CREATE TABLE IF NOT EXISTS amc_code_map (
        amc_code    TEXT PRIMARY KEY,
        amc_name    TEXT NOT NULL
    );

    -- ─────────────────────────────────────────────
    -- INDEXES
    -- ─────────────────────────────────────────────

    CREATE INDEX IF NOT EXISTS idx_bse_client_pan       ON bse_client_master(primary_holder_pan);
    CREATE INDEX IF NOT EXISTS idx_bse_client_mobile    ON bse_client_master(indian_mobile_no);
    CREATE INDEX IF NOT EXISTS idx_bse_sip_xsip         ON bse_sip(xsip_regn_no);
    CREATE INDEX IF NOT EXISTS idx_bse_sip_folio        ON bse_sip(folio_no);
    CREATE INDEX IF NOT EXISTS idx_bse_scheme_isin      ON bse_scheme_master(isin);
    CREATE INDEX IF NOT EXISTS idx_bse_scheme_rta       ON bse_scheme_master(rta_scheme_code);

    CREATE INDEX IF NOT EXISTS idx_cams_wbr4_folio      ON cams_wbr4_aum(foliochk);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr4_pan        ON cams_wbr4_aum(pan_no);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr9_folio      ON cams_wbr9_folio(foliochk);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr9_pan        ON cams_wbr9_folio(pan_no);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr2_folio      ON cams_wbr2_transaction(folio_no);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr2_pan        ON cams_wbr2_transaction(pan);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr2_traddate   ON cams_wbr2_transaction(traddate);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr49_folio     ON cams_wbr49_sip(folio_no);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr77_folio     ON cams_wbr77_brokerage(folio_no);
    CREATE INDEX IF NOT EXISTS idx_cams_wbr77_proc      ON cams_wbr77_brokerage(proc_date);

    CREATE INDEX IF NOT EXISTS idx_kfin_aum_folio       ON kfin_mfsd203_aum(folio_number);
    CREATE INDEX IF NOT EXISTS idx_kfin_folio_pan       ON kfin_mfsd211_folio(pan_number);
    CREATE INDEX IF NOT EXISTS idx_kfin_folio_inv       ON kfin_mfsd211_folio(folio);
    CREATE INDEX IF NOT EXISTS idx_kfin_txn_folio       ON kfin_mfsd201_transaction(td_acno);
    CREATE INDEX IF NOT EXISTS idx_kfin_txn_pan         ON kfin_mfsd201_transaction(pan1);
    CREATE INDEX IF NOT EXISTS idx_kfin_sip_folio       ON kfin_mfsd243_sip(folio);
    CREATE INDEX IF NOT EXISTS idx_kfin_brk_proc        ON kfin_mfsd205_brokerage(process_date);

    """)


if __name__ == "__main__":
    init_db()
